### ISSUE TITLE
Crash if Accompanist library is added.

### ISSUE THREAD

**Issue by Esarve** [adrielcafe/voyager#126]
I've included [Accompanist's system ui controller ](https://google.github.io/accompanist/systemuicontroller/) and after just adding this, I am facing crash in my navigation controller for voyager.

Heres's my code where it crashes

``` 
object HomeTab: Tab {
    override val options: TabOptions
        @Composable
        get() {
            val title = "HOME"
            val icon = rememberVectorPainter(Icons.Rounded.Home)

            return remember {
                TabOptions(
                    index = 0u,
                    title = "home",
                    icon = icon
                )
            }
        }

    @OptIn(ExperimentalAnimationApi::class)
    @Composable
    override fun Content() {
        Navigator(MainScreen()){
            SlideTransition(navigator = it)
        }
    }
}
```

and here is the crash log

```
 FATAL EXCEPTION: main
                                 Process: dev.souravdas.hush, PID: 32238
                                 java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~Ca3scZetqG1JuCxb2wVb0Q==/dev.souravdas.hush-bDGcXYU9WnIXoo0icv8oVg==/base.apk)
                                 	at cafe.adriel.voyager.transitions.ScreenTransitionKt.ScreenTransition(ScreenTransition.kt:46)
                                 	at cafe.adriel.voyager.transitions.SlideTransitionKt.SlideTransition(SlideTransition.kt:31)
                                 	at dev.souravdas.hush.nav.ComposableSingletons$VoyagerNavKt$lambda-1$1.invoke(VoyagerNav.kt:53)
                                 	at dev.souravdas.hush.nav.ComposableSingletons$VoyagerNavKt$lambda-1$1.invoke(VoyagerNav.kt:52)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$5$1.invoke(Navigator.kt:87)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$5$1.invoke(Navigator.kt:80)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$5.invoke(Navigator.kt:78)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$5.invoke(Navigator.kt:71)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt.Navigator(Navigator.kt:69)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt.Navigator(Navigator.kt:52)
                                 	at dev.souravdas.hush.nav.HomeTab.Content(VoyagerNav.kt:52)
                                 	at cafe.adriel.voyager.navigator.tab.TabKt$CurrentTab$1.invoke(Tab.kt:13)
                                 	at cafe.adriel.voyager.navigator.tab.TabKt$CurrentTab$1.invoke(Tab.kt:12)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                 	at cafe.adriel.voyager.navigator.Navigator$saveableState$2.invoke(Navigator.kt:136)
                                 	at cafe.adriel.voyager.navigator.Navigator$saveableState$2.invoke(Navigator.kt:135)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at cafe.adriel.voyager.core.lifecycle.ScreenLifecycleOwner$DefaultImpls.ProvideBeforeScreenContent(ScreenLifecycleOwner.kt:11)
                                 	at cafe.adriel.voyager.core.lifecycle.DefaultScreenLifecycleOwner.ProvideBeforeScreenContent(ScreenLifecycleOwner.kt:16)
                                 	at cafe.adriel.voyager.navigator.Navigator.saveableState(Navigator.kt:133)
                                 	at cafe.adriel.voyager.navigator.tab.TabNavigator.saveableState(TabNavigator.kt:54)
                                 	at cafe.adriel.voyager.navigator.tab.TabKt.CurrentTab(Tab.kt:12)
                                 	at cafe.adriel.voyager.navigator.tab.ComposableSingletons$TabNavigatorKt$lambda-1$1.invoke(TabNavigator.kt:20)
                                 	at cafe.adriel.voyager.navigator.tab.ComposableSingletons$TabNavigatorKt$lambda-1$1.invoke(TabNavigator.kt:20)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
20:05:53.379 AndroidRuntime   E  	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at cafe.adriel.voyager.navigator.tab.TabNavigatorKt$TabNavigator$1$1.invoke(TabNavigator.kt:35)
                                 	at cafe.adriel.voyager.navigator.tab.TabNavigatorKt$TabNavigator$1$1.invoke(TabNavigator.kt:34)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at cafe.adriel.voyager.navigator.tab.TabNavigatorKt$TabNavigator$1.invoke(TabNavigator.kt:34)
                                 	at cafe.adriel.voyager.navigator.tab.TabNavigatorKt$TabNavigator$1.invoke(TabNavigator.kt:29)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$5$1.invoke(Navigator.kt:87)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$5$1.invoke(Navigator.kt:80)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$5.invoke(Navigator.kt:78)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$5.invoke(Navigator.kt:71)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt.Navigator(Navigator.kt:69)
                                 	at cafe.adriel.voyager.navigator.NavigatorKt.Navigator(Navigator.kt:52)
                                 	at cafe.adriel.voyager.navigator.tab.TabNavigatorKt.TabNavigator(TabNavigator.kt:22)
                                 	at dev.souravdas.hush.activities.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:39)
                                 	at dev.souravdas.hush.activities.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:38)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:360)
                                 	at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
                                 	at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:73)
                                 	at dev.sourav.emptycompose.ui.theme.ThemeKt.HushTheme(Theme.kt:107)
                                 	at dev.souravdas.hush.activities.ComposableSingletons$MainActivityKt$lambda-2$1.invoke(MainActivity.kt:38)
                                 	at dev.souravdas.hush.activities.ComposableSingletons$MainActivityKt$lambda-2$1.invoke(MainActivity.kt:37)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
                                 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
                                 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
20:05:53.383 AndroidRuntime   E  	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:193)
                                 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
                                 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
                                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:158)
                                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:157)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:157)
                                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:142)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                 	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
                                 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3330)
                                 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3320)
                                 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                                 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                                 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3320)
                                 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3255)
                                 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
                                 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:966)
                                 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
                                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
                                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                                 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1104)
                                 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:133)
                                 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:183)
                                 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
                                 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
                                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
                                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                                 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1179)
                                 	at android.view.View.dispatchAttachedToWindow(View.java:20820)
                                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3550)
20:05:53.384 AndroidRuntime   E  	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3557)
                                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3557)
                                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3557)
                                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3557)
                                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2730)
                                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2234)
                                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9027)
                                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1105)
                                 	at android.view.Choreographer.doCallbacks(Choreographer.java:896)
                                 	at android.view.Choreographer.doFrame(Choreographer.java:815)
                                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1090)
                                 	at android.os.Handler.handleCallback(Handler.java:938)
                                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                                 	at android.os.Looper.loopOnce(Looper.java:201)
                                 	at android.os.Looper.loop(Looper.java:288)
                                 	at android.app.ActivityThread.main(ActivityThread.java:7886)
                                 	at java.lang.reflect.Method.invoke(Native Method)
                                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

everything goes back to normal If I remove that library

**Comment by YuriiShcherbiuk** [comment]
[#120](https://github.com/adrielcafe/voyager/issues/120)

**Comment by Syer10** [comment]
Use the version of Accompanist thats made to work for your version of compose. Accompanist likes to have beta/alpha versions that compile against the latest beta/alpha versions of compose.

**Comment by adrielcafe** [comment]
Now that Voyager is updated with Compose 1.5 on [1.0.0-rc07](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-rc07) you can use the latest Accompanist version.
