### ISSUE TITLE
Koin in Compose Multiplatform

### ISSUE THREAD

**Issue by hm-tamim** [adrielcafe/voyager#136]
Compose is not supported on iOS, so we need to write UIs in shared module.

Any way to use getScreenModel() in sharedModule with Koin?

Getting this crash:

```
                         FATAL EXCEPTION: main
                                                                                                    Process: com.myapplication.MyApplication, PID: 12790
                                                                                                    org.koin.core.error.NoBeanDefFoundException: No definition found for class:'java.lang.Object' q:''. Check your definitions!
                                                                                                    	at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:298)
                                                                                                    	at org.koin.core.scope.Scope.resolveValue(Scope.kt:268)
                                                                                                    	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
                                                                                                    	at org.koin.core.scope.Scope.get(Scope.kt:210)
                                                                                                    	at ui.screen.home.HomeScreen.Content(HomeScreen.kt:93)
```

**Comment by hm-tamim** [comment]
Oh, it works if you declare like this:

val viewModel =  getScreenModel<HomeViewModel>()

And doesn't work if

val viewModel: HomeViewModel by  getScreenModel()
