### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "void cafe.adriel.voyager.core.screen.Screen.Content(androidx.compose.runtime.Composer, int)"

### ISSUE THREAD

**Issue by markusressel** [adrielcafe/voyager#167]
Hey there,
I am running into this issue when trying to do a simple navigation to a screen that is located within another module.
The error occurs whether I use the `ScreenRegistry` or not.
The Screen in question looks like this:

```kotlin
class WebViewScreen(
    private val params: WebViewAddOnParams,
) : AndroidScreen() {

    @Composable
    override fun Content() {
        WebViewDefaultScreen(params = params)
    }
}
```

The navigation call in the parent looks like this:

```kotlin

object HomeTab : Tab {
    ...
    @Composable
    override fun Content() {
        val navigator = LocalNavigator.currentOrThrow.parent!!

        val params = WebViewAddOnParams()
        val sharedScreen = WebViewSharedScreen.Default(params)
        // val rememberedScreen = rememberScreen(sharedScreen)
        val directScreen = remember { WebViewScreen(params) }

        Button(
            onClick = {
                navigator.push(directScreen)
            },
        ) {
            Text("Web")
        } 
    }
}
```

Both navigating directly as well as navigating via the shared screen gives the same error.

Any idea what causes this?

```
java.lang.AbstractMethodError: abstract method "void cafe.adriel.voyager.core.screen.Screen.Content(androidx.compose.runtime.Composer, int)"
                                                                                                    	at cafe.adriel.voyager.navigator.NavigatorKt$CurrentScreen$1.invoke(Navigator.kt:46)
                                                                                                    	at cafe.adriel.voyager.navigator.NavigatorKt$CurrentScreen$1.invoke(Navigator.kt:45)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                                                                                    	at cafe.adriel.voyager.navigator.Navigator$saveableState$2.invoke(Navigator.kt:152)
                                                                                                    	at cafe.adriel.voyager.navigator.Navigator$saveableState$2.invoke(Navigator.kt:151)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt$RecursiveProvideBeforeScreenContent$4.invoke(multipleScreenLifecycleOwnerUtil.kt:60)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt$RecursiveProvideBeforeScreenContent$4.invoke(multipleScreenLifecycleOwnerUtil.kt:59)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner$ProvideBeforeScreenContent$1$1.invoke(AndroidScreenLifecycleOwner.kt:105)
                                                                                                    	at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner$ProvideBeforeScreenContent$1$1.invoke(AndroidScreenLifecycleOwner.kt:104)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner$ProvideBeforeScreenContent$1.invoke(AndroidScreenLifecycleOwner.kt:104)
                                                                                                    	at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner$ProvideBeforeScreenContent$1.invoke(AndroidScreenLifecycleOwner.kt:99)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                                                                                    	at cafe.adriel.voyager.navigator.Navigator.saveableState$provideSaveableState(Navigator.kt:139)
                                                                                                    	at cafe.adriel.voyager.navigator.Navigator.access$saveableState$provideSaveableState(Navigator.kt:101)
                                                                                                    	at cafe.adriel.voyager.navigator.Navigator$saveableState$1.invoke(Navigator.kt:150)
                                                                                                    	at cafe.adriel.voyager.navigator.Navigator$saveableState$1.invoke(Navigator.kt:150)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt$RecursiveProvideBeforeScreenContent$3.invoke(multipleScreenLifecycleOwnerUtil.kt:57)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt$RecursiveProvideBeforeScreenContent$3.invoke(multipleScreenLifecycleOwnerUtil.kt:56)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
2023-06-20 18:07:58.306 22664-22664 AndroidRuntime              E  	at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner.ProvideBeforeScreenContent(AndroidScreenLifecycleOwner.kt:99)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt.RecursiveProvideBeforeScreenContent(multipleScreenLifecycleOwnerUtil.kt:55)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt.access$RecursiveProvideBeforeScreenContent(multipleScreenLifecycleOwnerUtil.kt:1)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt$RecursiveProvideBeforeScreenContent$recursiveContent$1.invoke(multipleScreenLifecycleOwnerUtil.kt:39)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt$RecursiveProvideBeforeScreenContent$recursiveContent$1.invoke(multipleScreenLifecycleOwnerUtil.kt:38)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt$RecursiveProvideBeforeScreenContent$2.invoke(multipleScreenLifecycleOwnerUtil.kt:51)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt$RecursiveProvideBeforeScreenContent$2.invoke(multipleScreenLifecycleOwnerUtil.kt:50)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:162)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2486)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2777)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.ScreenLifecycleOwner$DefaultImpls.ProvideBeforeScreenContent(ScreenLifecycleOwner.kt:18)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.DefaultScreenLifecycleOwner.ProvideBeforeScreenContent(ScreenLifecycleOwner.kt:26)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt.RecursiveProvideBeforeScreenContent(multipleScreenLifecycleOwnerUtil.kt:46)
                                                                                                    	at cafe.adriel.voyager.core.lifecycle.MultipleScreenLifecycleOwnerUtilKt.MultipleProvideBeforeScreenContent(multipleScreenLifecycleOwnerUtil.kt:18)
                                                                                                    	at cafe.adriel.voyager.navigator.Navigator.saveableState(Navigator.kt:148)
                                                                                                    	at cafe.adriel.voyager.navigator.NavigatorKt.CurrentScreen(Navigator.kt:45)
                                                                                                    	at cafe.adriel.voyager.navigator.NavigatorKt$CurrentScreen$2.invoke(Unknown Source:4)
                                                                                                    	at cafe.adriel.voyager.navigator.NavigatorKt$CurrentScreen$2.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:162)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2486)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2754)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3385)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3363)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3363)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3328)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:772)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1047)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:541)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
2023-06-20 18:07:58.309 22664-22664 AndroidRuntime              E  	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1317)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1328)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:940)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:869)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8170)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by programadorthi** [comment]
Complaining about abstract method? `java.lang.AbstractMethodError: abstract method `
I think that can be related to Compose Compiler.
Can you share with us your Kotlin and Compose setup? A sample should help us too.

**Comment by K1rakishou** [comment]
@markusressel 
Do you have multiple modules in your app? Then check if you have enabled compose in the module where the screen is located. Had the same issue just a little while ago.

**Comment by markusressel** [comment]
Thx @K1rakishou , thats the solution!
Somehow I assumed the plugin would be applied through other means already so I didn't think to check this.
Adding the compose plugin to the module in question fixed the error 🎉
