### ISSUE TITLE
Crash when putting app to background

### ISSUE THREAD

**Issue by alfietapping** [adrielcafe/voyager#180]
I have a situation whereby I've made a dialog composable into a screen as i need it to manage its own state and events. It works fine as expected, but if i put the back to the background while the dialog is in view it throws the error i've put below.

```
data class SubscriptionContent(
    val onDismiss: () -> Unit
): Screen {

    override val key: ScreenKey = "subscription"

    @Composable
    override fun Content() {

        val screenModel = rememberScreenModel<SubscriptionDialogViewModel>()
        val state by screenModel.state.collectAsState()

        SubscriptionDialog(state = state, event = screenModel)

        LaunchedEffect(key1 = screenModel.navigationEvent) {
            screenModel.navigationEvent.collect {
                when (it) {
                    NavigateBack -> onDismiss()
                    else -> Unit
                }
            }
        }
    }
}
```

FATAL EXCEPTION: main
                                                                                                    Process: com.XXX, PID: 24430
                                                                                                    android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = com.XXXcore_navigation.SubscriptionContent)
                                                                                                    	at android.os.Parcel.writeSerializable(Parcel.java:2751)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2517)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2316)
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1382)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2460)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2316)
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1382)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2460)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2316)
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1389)
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1334)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2433)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2323)
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1389)
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1334)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2433)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2323)
                                                                                                    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1874)
                                                                                                    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1911)
                                                                                                    	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:142)
                                                                                                    	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:158)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.io.NotSerializableException: cafe.adriel.voyager.navigator.Navigator
                                                                                                    	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
                                                                                                    	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
                                                                                                    	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
                                                                                                    	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
                                                                                                    	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
                                                                                                    	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
                                                                                                    	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
                                                                                                    	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
                                                                                                    	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
                                                                                                    	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
                                                                                                    	at android.os.Parcel.writeSerializable(Parcel.java:2746)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2517) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2316) 
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1382) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2460) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2316) 
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1382) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2460) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2316) 
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265) 
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802) 
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1389) 
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1334) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2433) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2323) 
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265) 
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802) 
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1389) 
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1334) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2433) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2323) 
                                                                                                    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1874) 
                                                                                                    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1911) 
                                                                                                    	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:142) 
                                                                                                    	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:158) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by Syer10** [comment]
See #59
This is expected behavior
