### ISSUE TITLE
Crash when ScreenTransistion is started more than once

### ISSUE THREAD

**Issue by CodeQuacker** [adrielcafe/voyager#188]
Tested on:
- Compose 1.5.0
- Voyager 1.0.0-rc06

To replicate:

1. Have 2 screens and button to change from 1st to 2nd and navigator with screen transistions set up
2. Press button more than once in quick succession.

Is it desired outcome (based on error message)?

Error:
```
FATAL EXCEPTION: main
	Process: <package name>, PID: 24367
	java.lang.IllegalArgumentException: Key <package name>.RegisterScreen:transition was used multiple times 
		at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:89)
		at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:88)
		at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
		at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
		at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
		at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
		at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:625)
		at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
		at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
		at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
		at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
		at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
		at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1158)
		at android.view.Choreographer.doCallbacks(Choreographer.java:950)
		at android.view.Choreographer.doFrame(Choreographer.java:874)
		at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1142)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:211)
		at android.os.Looper.loop(Looper.java:300)
		at android.app.ActivityThread.main(ActivityThread.java:8301)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1043)
		Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@9f85fcf, androidx.compose.ui.platform.MotionDurationScaleImpl@50c0d5c, StandaloneCoroutine{Cancelling}@35be865, AndroidUiDispatcher@20ee93a]
```

**Comment by CodeQuacker** [comment]
Found closed issue of the same problem. Closing #23

**Comment by CodeQuacker** [comment]
Found closed issue of the same problem. Closing #23
