### ISSUE TITLE
BottomSheetNavigator is not compatible with Compose 1.5.0.

### ISSUE THREAD

**Issue by 0xZhangKe** [adrielcafe/voyager#191]
voyager version is `1.0.0-rc06`
compose version is `1.5.0`

It looks like they're not compatible with each other.

```
java.lang.NoSuchMethodError: No static method ModalBottomSheetLayout-BzaUkTc(Lkotlin/jvm/functions/Function3;Landroidx/compose/ui/Modifier;Landroidx/compose/material/ModalBottomSheetState;Landroidx/compose/ui/graphics/Shape;FJJJLkotlin/jvm/functions/Function2;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/material/ModalBottomSheetKt; or its super classes (declaration of 'androidx.compose.material.ModalBottomSheetKt' appears in /data/app/~~2keLmjvRDnowKpkjtc6A-g==/com.zhangke.voyagerdemo-o7aa75K--w9llbWgGA-Kaw==/base.apk)
                 	at cafe.adriel.voyager.navigator.bottomSheet.BottomSheetNavigatorKt$BottomSheetNavigator$1$2.invoke(BottomSheetNavigator.kt:77)
                 	at cafe.adriel.voyager.navigator.bottomSheet.BottomSheetNavigatorKt$BottomSheetNavigator$1$2.invoke(BottomSheetNavigator.kt:76)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at cafe.adriel.voyager.navigator.bottomSheet.BottomSheetNavigatorKt$BottomSheetNavigator$1.invoke(BottomSheetNavigator.kt:76)
                 	at cafe.adriel.voyager.navigator.bottomSheet.BottomSheetNavigatorKt$BottomSheetNavigator$1.invoke(BottomSheetNavigator.kt:69)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$6$1.invoke(Navigator.kt:96)
                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$6$1.invoke(Navigator.kt:89)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$6.invoke(Navigator.kt:87)
                 	at cafe.adriel.voyager.navigator.NavigatorKt$Navigator$6.invoke(Navigator.kt:80)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at cafe.adriel.voyager.navigator.NavigatorKt.Navigator(Navigator.kt:78)
                 	at cafe.adriel.voyager.navigator.NavigatorKt.Navigator(Navigator.kt:58)
                 	at cafe.adriel.voyager.navigator.bottomSheet.BottomSheetNavigatorKt.BottomSheetNavigator-zm8iufA(BottomSheetNavigator.kt:69)
                 	at com.zhangke.voyagerdemo.ComposableSingletons$MainActivityKt$lambda-3$1.invoke(MainActivity.kt:27)
                 	at com.zhangke.voyagerdemo.ComposableSingletons$MainActivityKt$lambda-3$1.invoke(MainActivity.kt:26)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
                 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
                 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:195)
22:10:21.633  E  	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
                 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:158)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:157)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:157)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:142)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
                 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3340)
                 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3273)
                 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:588)
                 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1013)
                 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1191)
                 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:133)
                 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:183)
                 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
                 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1266)
                 	at android.view.View.dispatchAttachedToWindow(View.java:21290)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2820)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                 	at android.view.Choreographer.doFrame(Choreographer.java:832)
22:10:21.633  E  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7872)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
22:10:21.642  I  Sending signal. PID: 18221 SIG: 9

```

I tried copying out the BottomSheetNavigator code and setting the correct function signature, but still had other problems.

cafe.adriel.voyager.navigator.bottomSheet.BottomSheetNavigator#show will throw this error:

```
 kotlinx.coroutines.JobCancellationException: ScopeCoroutine was cancelled; job=ScopeCoroutine{Cancelled}
```

**Comment by WorriedMan** [comment]
I also copied the BottomSheetNavigator to get the correct function signature. But when I attempted to show a bottom sheet, my app froze due to circular calls between confirmStateChange on line 58 and public fun hide() on line 114. As a workaround I commented out line 65 hideBottomSheet?.invoke(). Now, everything seems to be working properly.
