### ISSUE TITLE
Beta13  hiltviewmodel crash when navigating back to same destination

### ISSUE THREAD

**Issue by Tolriq** [adrielcafe/voyager#20]
So the fix for the replace issue have now generated a worse issue.

```
    java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
        at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.java:111)
        at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.java:50)
        at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:70)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:84)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:109)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:171)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
```

it will crash whenever you navigate again to a destination.

So push(Screen) pop() push(Screen) will crash.

As said in https://github.com/adrielcafe/voyager/issues/17 the root issue is more about transitions and autodispose happening too early.

There's side effects too with ScreenModel that are disposed too early (even before the next screen is composed). This can corrupt what is displayed during transition and cause hard to diagnose side effects.

This is more a core issue for @adrielcafe than an hilt specific one. (The "fix" stills needs to be reverted)
While we can disable autodispose at the navigator level we have no way to built custom transitions that would do a proper dispose after the end of the transition.

**Comment by programadorthi** [comment]
Hi @Tolriq. This issue happens because using @HiltViewModel couple it instance creation to the default ViewModelFactory provided by Hilt and your own StateRegistry that is the current Activity.
We have overrided this behavior to use voyager `AndroidScreenLifecycleOwner` instead. Checkout #21

**Comment by Tolriq** [comment]
Well I know my English is bad but the dispose too early issue is real too :) I'll open another outside of the crashes if necessary.

BTW
```
internal val Context.componentActivity: ComponentActivity
    get() = this as? ComponentActivity
``` 
Is not covering all cases, from discussions with Compose team there's cases when LocalContent.current can be a context wrapper and you need to check the baseContext until you find it

```
fun Context.findComponentActivity(): ComponentActivity? = when (this) {
    is ComponentActivity-> this
    is ContextWrapper -> baseContext.findActivity()
    else -> null
}
```

**Comment by programadorthi** [comment]
Hey guys, the voyager owner is very busy and his wife is pregnant. Updates will come soon. Stay up to date.

**Comment by Tolriq** [comment]
I hope he have stored enough sleep :) He's next 1,5 years will remove a lot of it :p
