### ISSUE TITLE
Crash durring animation Key com.github.navtest.ScreenFoo was used multiple times 

### ISSUE THREAD

**Issue by jershell** [adrielcafe/voyager#23]
Hello, my application crashes when changing screens with animated content.
I use code from examples. I think is a problem for all users.

kotlin_version '1.5.31'
voyager_version = "1.0.0-beta13"
compose_version = '1.1.0-alpha06'

Repository for reproduce - https://github.com/jershell/voyager-bug-reproduce/tree/main

Flow
1. Click on the button "to Bar"
2. Not awaiting finishing of animation fast click on the button "to Foo"
Have a crash

```java.lang.IllegalArgumentException: Key com.github.navtest.ScreenFoo was used multiple times ```

Stacktrace
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.navtest, PID: 2788
    java.lang.IllegalArgumentException: Key com.github.navtest.ScreenFoo was used multiple times 
        at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:89)
        at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:88)
        at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
        at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:802)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:647)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:488)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

**Comment by adrielcafe** [comment]
@jershell closing the issue now, but feel free to reopen if the crash persists.

Thanks for your help @programadorthi !
