### ISSUE TITLE
IllegalArgumentException:  Key Screen:transition was used multiple times 

### ISSUE THREAD

**Issue by j-roskopf** [adrielcafe/voyager#262]
Hey! Have been using the library for awhile and I've really liked it!

Using the latest RC-10, Kotlin 1.9.20, Compose 1.5.10, there is an issue I run into when I quickly double click a button that navigates to another screen in my Compose Multiplatform project.

Minimum reproducible code:

```
// main entry point from the relevant platform
@Composable
fun Main() {
    Navigator(FirstScreen()) { navigator ->
        SlideTransition(navigator)
    }
}

class FirstScreen : Screen {
    @Composable
    override fun Content() {
        val navigator = LocalNavigator.currentOrThrow
        Button({
            navigator.push(NewScreen())
        }) {
            Text("Click")
        }
    }
}

class NewScreen : Screen {
    @Composable
    override fun Content() {
        Text("Hello")
    }
}
```

Is this crash expected / should I be debouncing my button clicks manually?

Thanks!

Full stack trace:

```
java.lang.IllegalArgumentException: Key com.joetr.sync.sphere.ui.previous.PreviousRoomScreen:transition was used multiple times
at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:89)
at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:88)
at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:625)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
at android.view.Choreographer.doCallbacks(Choreographer.java:952)
at android.view.Choreographer.doFrame(Choreographer.java:878)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by hypergonial** [comment]
I ran into this while trying to nest a `TabNavigator` into a `Navigator` funnily enough.

**Comment by diegoberaldin** [comment]
I had a similar problem or, rather, the same exception in a slightly different scenario.

I had a screen showing a detail about an item which could optionally open a screen to show the detail about a "related" item. 

These were two different instances of the same Screen subclass. Without transitions everything worked fine, when adding transitions opening the related screen crashed with the `transition was used multiple times` error.

Solution: overriding the key property and return a custom unique key, in my case concatenating the item ID was enough since in my context the relation is not reflexive so no two instances of the same screen with the same ID can ever be adjacent.

PS: If the navigation is A -> B -> A (the relation is symmetric) no issue and no crash whatsoever.

**Comment by ArleyPereira** [comment]
Same problem here...

it looks like androidx.lifecycle:lifecycle added dropUnlessResumed in version 2.8.0-alpha02.

https://developer.android.com/jetpack/androidx/releases/lifecycle?hl=pt-br

I tested with version 2.8.0-rc01, but I got the error: CompositionLocal LocalLifecycleOwner not present.

voyager = "1.1.0-alpha04"
composeBom = "2024.05.00"
kotlin = "1.9.23"

```
FATAL EXCEPTION: main (Ask Gemini)
Process: br.com.hellodev.find360, PID: 15156
java.lang.IllegalArgumentException: Key br.com.hellodev.signup.presenter.screens.register.screen.RegisterScreen:transition was used multiple times
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:89)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:88)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:83)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1295)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:984)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1005)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:639)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1648)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
	at android.view.Choreographer.doFrame(Choreographer.java:1045)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@a7d1990, androidx.compose.ui.platform.MotionDurationScaleImpl@a6df289, StandaloneCoroutine{Cancelling}@fac328e, AndroidUiDispatcher@b8cfaaf]
```

**Comment by Kate941-su** [comment]
I met the same problem. In my case the reason why I came across this error was that `replaceAll()` function was called the screen that was placed inside the Tab. 

I fixed that `replaceAll()` was called the screen that defines Tabs.

In summary, Please check that you call `replaceAll()` as the proper place again.
