### ISSUE TITLE
Transitions crashing after v1.0.0 migration

### ISSUE THREAD

**Issue by Smoothie1-ini** [adrielcafe/voyager#279]
FATAL EXCEPTION: main
                                                                                                    Process: com.example.trippin, PID: 5148
                                                                                                    java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Ljava/lang/String;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~WBD_ERPbPgNZU5uhfDjM4Q==/com.example.trippin-YvVc4Vis54eUw2zK2lo7dg==/base.apk)
                                                                                                    	at cafe.adriel.voyager.transitions.ScreenTransitionKt.ScreenTransition(ScreenTransition.kt:43)
                                                                                                    	at cafe.adriel.voyager.transitions.SlideTransitionKt.SlideTransition(SlideTransition.kt:29)
                                                                                                    	at com.example.trippin.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:17)
                                                                                                    	at com.example.trippin.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:16)

**Comment by Smoothie1-ini** [comment]
was working just fine in v1.0.0-rc05

**Comment by Syer10** [comment]
Make sure you have fully updated your Compose version with Voyager. Voyager only supports the latest stable version of Compose.

**Comment by Smoothie1-ini** [comment]
Thanks a lot, migrating compose BOM to latest version fixed the issue.
