### ISSUE TITLE
java.lang.IllegalArgumentException: Key screens.ScreenD:transition was used multiple times 

### ISSUE THREAD

**Issue by BasharAlhalabi** [adrielcafe/voyager#285]
Can't prevent this as I reuse the screen d from a drawer (at least in android) : 

FATAL EXCEPTION: main
                                                                                                    Process: com.myapplication.myapplication, PID: 20160
                                                                                                    java.lang.IllegalArgumentException: Key screens.ScreenD:transition was used multiple times 
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:89)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:88)
                                                                                                    	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
                                                                                                    	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:625)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)

**Comment by BasharAlhalabi** [comment]
Found a method by adding withing screen:

    override val key: ScreenKey
        get() = uniqueScreenKey

**Comment by Syer10** [comment]
That is a horrible way to set the unique key, you need to save the value like this
```
override val key: ScreenKey = uniqueScreenKey
```

You are likely causing bugs by using `get()`, since get does not save the value for later, and so you are generating a new key each time the key is accessed.

**Comment by BasharAlhalabi** [comment]
@Syer10 thanks for correction!
