### ISSUE TITLE
ViewModel and injected property issue with Hilt

### ISSUE THREAD

**Issue by galex** [adrielcafe/voyager#311]
Hello,

I'm trying out Voyager which seems amazing but I'm stuck on using an Android ViewModel within a Screen.
The screen:
```kotlin
class SignupScreen: Screen {

    @Composable
    override fun Content() {
        val screenModel: SignupScreenModel = getScreenModel()
        val viewModel: SignupViewModel = getViewModel()
        Text("Signup Screen right here!")
    }
}
```
A ViewModel with an empty constructor works:
```kotlin
@HiltViewModel
class SignupViewModel @Inject constructor(): ViewModel() 
```
But as soon as I add a property to inject, it doesn't:
```kotlin
@HiltViewModel
class SignupViewModel @Inject constructor(
    private val signupUseCase: SignupUseCase,
): ViewModel()
```
The error is the following:
```java
FATAL EXCEPTION: main
Process:  com.company, PID: 30741
    java.lang.RuntimeException: Cannot create an instance of class com.company.feature.SignupViewModel
(...)
Caused by: java.lang.NoSuchMethodException: com.company.feature.SignupViewModel.<init> []
    at java.lang.Class.getConstructor0(Class.java:3325)
    at java.lang.Class.getDeclaredConstructor(Class.java:3063)
    at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.kt:199)
```
Calling the same ViewModel from the only Activity works:
```kotlin
val viewModel: SignupViewModel by viewModels()
```
ScreenModel does work with an injected property:
```kotlin
class SignupScreenModel @Inject constructor(
    private val signupUseCase: SignupUseCase,
): ScreenModel
```
Some more info/comments:
- The setup is a simple multi-module Android App with Hilt/Dagger.
- The [Hilt Integration documentation](https://voyager.adriel.cafe/screenmodel/hilt-integration) doesn't mention the need of setting up MultiBindings which comes as a surprise
- There is a mention in the docs of an `AndroidScreen()` which could help but I can't find it, was that removed? What replaces it?

So the question is, why is it still looking for an empty constructor? What am I missing?
Thanks in advance! :pray:

**Comment by Anatoly4444** [comment]
I facing the same issue. I don't have empty constructor in my ViewModel class but factory trying to call it

**Comment by slickorange** [comment]
I am getting the same issue, version 1.1.0-beta02. It was still working on version 1.0.0-rc09 (I did not test the versions in between)

**Comment by imneeraj** [comment]
Did anyone found the solution to this issue

**Comment by LewisFieldMargin** [comment]
I could not find a solution other than downgrading to 1.0.0
