### ISSUE TITLE
[KMP ViewModels][Voyager][Koin] Crush if you try to navigate back

### ISSUE THREAD

**Issue by RomanKarpilenko** [adrielcafe/voyager#450]
Hello everyone! In my test project, I am trying to implement Navigator Scoped ViewModel so that when the navigator on the screen is destroyed, the ViewModel is also destroyed. However, when I try to do this, the application crashes. Here is a simple example of how I am trying to do this:

```
@OptIn(ExperimentalVoyagerApi::class, KoinExperimentalAPI::class)
@Composable
inline fun <reified VM : ViewModel> navigatorKoinViewModel(
    navigator: Navigator,
    key: String? = null,
    scope: Scope = currentKoinScope(),
    noinline parameters: ParametersDefinition? = null,
): VM {
    val owner = navigator.rememberNavigatorViewModelStoreOwner()
    return koinViewModel(
        viewModelStoreOwner = owner,
        key = key,
        scope = scope,
        parameters = parameters
    )
}
```

```
@Composable
fun App() {
    Navigator(
        screen = SplashScreen()
    ) { rootNavigator ->
        // As I understand, this viewModel should be alive while root navigator is alive
        val mainViewModel: MainViewModel = navigatorKoinViewModel(
            navigator = rootNavigator
        )
        //...
        
        Navigator(
            screen = LoginScreen
        ) { loginFlowNavigator ->
            // As I understand, this viewModel should be alive while loginFlowNavigator is alive
            val loginViewModel: LoginViewModel = navigatorKoinViewModel(
                navigator = loginFlowNavigator,
            )
            //...
            
            //And when I try do this, I expect that LoginViewModel will be removed, because loginFlowNavigator will be destroyed
            loginFlowNavigator.pop()
        }
    }
}
```

But after pop the LoginScreen, I get the crush:
```
java.lang.IllegalStateException: State must be at least CREATED to move to DESTROYED, but was INITIALIZED in component cafe.adriel.voyager.jetpack.VoyagerLifecycleKMPOwner@a1a2dc4
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.jvm.kt:131)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.jvm.kt:124)
	at cafe.adriel.voyager.jetpack.VoyagerLifecycleKMPOwner.safeHandleLifecycleEvent(VoyagerLifecycleKMPOwner.kt:195)
	at cafe.adriel.voyager.jetpack.VoyagerLifecycleKMPOwner.onDispose(VoyagerLifecycleKMPOwner.kt:111)
	at cafe.adriel.voyager.jetpack.NavigatorLifecycleKMPOwner.onDispose(NavigatorLifecycleKMPOwner.kt:28)
	at cafe.adriel.voyager.navigator.lifecycle.NavigatorLifecycleStore.remove(NavigatorLifecycleStore.kt:41)
	at cafe.adriel.voyager.navigator.internal.NavigatorDisposableKt.disposeNavigator(NavigatorDisposable.kt:80)
	at cafe.adriel.voyager.navigator.internal.NavigatorDisposableKt$NavigatorDisposableEffect$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:498)
	at cafe.adriel.voyager.core.lifecycle.DisposableEffectIgnoringConfigurationImpl.onForgotten(DisposableEffect.kt:71)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1276)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:984)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1005)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:639)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@68a189f, androidx.compose.ui.platform.MotionDurationScaleImpl@6471dec, StandaloneCoroutine{Cancelling}@7edd5b5, AndroidUiDispatcher@65f544a]
```

What can I do wrong? Thank you!

**Comment by mainrs** [comment]
Were you able to solve the issue?

**Comment by orcchg** [comment]
same issue, seems to be some bug in Voyager in relation with androidx.lifecycle. I tried two approches: using `ScreenModel` and using `ViewModel`. The latter crashes with this exception while trying to restore screen. Minimal reproducible example:

```
Screen {
    @Composable
    fun Content() {
        val vm = navigatorViewModel { MyViewModel() }
    }
}
```

enable `Don't keep activities`

minimize then restore App from recent tasks - it will crash with this exception.

**Comment by AliAzaz** [comment]
any possible way to resolve this state crash?
