### ISSUE TITLE
Crashing When The App Starts Up Again, After been Minimized For a period of Time

### ISSUE THREAD

**Issue by afolabisamguy** [adrielcafe/voyager#473]
E  FATAL EXCEPTION: main (Ask Gemini)
 Process: com.alphatech.crypto, PID: 18497                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object kotlin.jvm.functions.Function1.invoke(java.lang.Object)' on a null object reference
                                                                                                    	at presentation.tabs.HomeTab$Content$1$1.invokeSuspend(HomeTab.kt:49)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:264)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7684)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:507)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@2cb490e, androidx.compose.runtime.BroadcastFrameClock@fa48f2f, StandaloneCoroutine{Cancelling}@a0b793c, AndroidUiDispatcher@63b16c5]

**Comment by nvkleban** [comment]
Add some code, what is happening in your HomeTab.Content
