### ISSUE TITLE
ReferenceError: getCachedJsObject is not defined

### ISSUE THREAD

**Issue by basurahan** [adrielcafe/voyager#482]
Hi I am unable to run my KMP wasm target with voyager I kept getting this exception that I have no idea is refering to 
```
getCachedJsObject is not defined
ReferenceError: getCachedJsObject is not defined
    at kotlin.wasm.internal.getCachedJsObject_$external_fun (webpack-internal:///./kotlin/composeApp.uninstantiated.mjs:120:78)
    at <RedditLite:composeApp>.kotlin.wasm.internal.getCachedJsObject_$external_fun__externalAdapter (http://localhost:8080/composeApp.wasm:wasm-function[12944]:0x2c65fc)
    at <RedditLite:composeApp>.kotlin.wasm.internal.externRefToAny (http://localhost:8080/composeApp.wasm:wasm-function[12906]:0x2c6375)
    at <RedditLite:composeApp>.kotlin.wasm.internal.jsToKotlinAnyAdapter (http://localhost:8080/composeApp.wasm:wasm-function[12905]:0x2c6348)
    at <RedditLite:composeApp>.androidx.compose.ui.window.ComposeViewport (http://localhost:8080/composeApp.wasm:wasm-function[43934]:0x530ddf)
    at <RedditLite:composeApp>.link.limecode.reddit.lite.main (http://localhost:8080/composeApp.wasm:wasm-function[52867]:0x5f4cd1)
    at <RedditLite:composeApp>.kotlin.wasm.internal.mainCallsWrapper (http://localhost:8080/composeApp.wasm:wasm-function[52879]:0x5f953a)
    at <RedditLite:composeApp>._initialize (http://localhost:8080/composeApp.wasm:wasm-function[52880]:0x5f9546)
    at instantiate (webpack-internal:///./kotlin/composeApp.uninstantiated.mjs:5703:21)
    at async eval (webpack-internal:///./kotlin/composeApp.mjs:18:18)
```

**Comment by basurahan** [comment]
I think its not related to voyager closing this for now

**Comment by muazkadan** [comment]
It's probably related to [ktor](https://github.com/ktorio/ktor) as I got the same error when I updated from ktor 3.0.0-beta-2 to 3.0.0-rc-1

**Comment by basurahan** [comment]
for me its kotlinx-serialization here is the story https://youtrack.jetbrains.com/issue/CMP-6658
