### ISSUE TITLE
android.os.BadParcelableException: Parcelable encountered IOException when screen is off

### ISSUE THREAD

**Issue by hafiz013** [adrielcafe/voyager#488]
sample edit screen:
```
class EditScreen(private val asset: AssetTable, private val categoryAsset: String,
                      private val typeOfAsset: String
):BasedActivityScreen() {
     @Preview
    @Composable
    override fun previewScreen() {
  }
}

abstract class BasedActivityScreen : Screen{
    @Composable
    override fun Content() {
        val navigator = LocalNavigator.currentOrThrow

        val sessionState: SessionState = koinInject()
        val sessionUiState by sessionState.isLoggedIn.collectAsState()

        if (!sessionUiState){
            LaunchedEffect(Unit){
                delay(3000)
                navigator.replace(LoginScreen())
            }
        }

        previewScreen()
    }

    @Preview
    @Composable
    open fun previewScreen(){}
}
```
Error:
```
Process: com.kloudius.katmaans, PID: 19238
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = com.sample.editScreen)
	at android.os.Parcel.writeSerializable(Parcel.java:2807)
	at android.os.Parcel.writeValue(Parcel.java:2573)
	at android.os.Parcel.writeValue(Parcel.java:2372)
	at android.os.Parcel.writeList(Parcel.java:1425)
	at android.os.Parcel.writeValue(Parcel.java:2516)
	at android.os.Parcel.writeValue(Parcel.java:2372)
	at android.os.Parcel.writeList(Parcel.java:1425)
	at android.os.Parcel.writeValue(Parcel.java:2516)
	at android.os.Parcel.writeValue(Parcel.java:2372)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1308)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1847)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1377)
	at android.os.Parcel.writeValue(Parcel.java:2489)
	at android.os.Parcel.writeValue(Parcel.java:2379)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1308)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1847)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1377)
	at android.os.Parcel.writeValue(Parcel.java:2489)
	at android.os.Parcel.writeValue(Parcel.java:2379)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1921)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1958)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
```

library use:
voyager = "1.1.0-alpha04"

**Comment by comm1x** [comment]
Same for 1.1.0-beta03

**Comment by gregriggins36** [comment]
@hafiz013  is `AssetTable` `@Serializable`?

**Comment by vandermast2** [comment]
I have the same problem.
