### ISSUE TITLE
Custom transition made app crashed when goes to background, even using Parcelable

### ISSUE THREAD

**Issue by devahmedshendy** [adrielcafe/voyager#507]
I have following voyager screen, with custom fade transition:
```kotlin
// screen
data class SplashVoygarScreen(
    val delegate: SplashScreenDelegate
): Screen, ScreenTransition by FadeTransition() {

    // Properties

    override val key: ScreenKey = uniqueScreenKey

    // View

    @Composable
    override fun Content() {
        val viewModel = rememberScreenModel {
            SplashScreenViewModel(
                business = SplashScreenBusiness(
                    database = DefaultWorker()
                )
            )
        }

        SplashScreen(viewModel = viewModel, delegate = delegate)
    }
}

// transition
final class FadeTransition: ScreenTransition {
    override fun enter(lastEvent: StackEvent): EnterTransition {
        return fadeIn(tween(500))
    }

    override fun exit(lastEvent: StackEvent): ExitTransition {
        return fadeOut(tween(500))
    }
}
```

When I put app on background, the app gets crashed
```
FATAL EXCEPTION: main
Process: com.bundeid, PID: 11193
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = com.bundeid.features.splash.view.SplashVoygarScreen)
	at android.os.Parcel.writeSerializable(Parcel.java:2809)
	at android.os.Parcel.writeValue(Parcel.java:2575)
	at android.os.Parcel.writeValue(Parcel.java:2374)
	at android.os.Parcel.writeList(Parcel.java:1427)
	at android.os.Parcel.writeValue(Parcel.java:2518)
	at android.os.Parcel.writeValue(Parcel.java:2374)
	at android.os.Parcel.writeList(Parcel.java:1427)
	at android.os.Parcel.writeValue(Parcel.java:2518)
	at android.os.Parcel.writeValue(Parcel.java:2374)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1917)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1954)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.io.NotSerializableException: com.bundeid.core.navigation.FadeTransition
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2804)
	at android.os.Parcel.writeValue(Parcel.java:2575) 
	at android.os.Parcel.writeValue(Parcel.java:2374) 
	at android.os.Parcel.writeList(Parcel.java:1427) 
	at android.os.Parcel.writeValue(Parcel.java:2518) 
	at android.os.Parcel.writeValue(Parcel.java:2374) 
	at android.os.Parcel.writeList(Parcel.java:1427) 
	at android.os.Parcel.writeValue(Parcel.java:2518) 
	at android.os.Parcel.writeValue(Parcel.java:2374) 
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310) 
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843) 
	at android.os.Bundle.writeToParcel(Bundle.java:1389) 
	at android.os.Parcel.writeBundle(Parcel.java:1379) 
	at android.os.Parcel.writeValue(Parcel.java:2491) 
	at android.os.Parcel.writeValue(Parcel.java:2381) 
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310) 
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843) 
	at android.os.Bundle.writeToParcel(Bundle.java:1389) 
	at android.os.Parcel.writeBundle(Parcel.java:1379) 
	at android.os.Parcel.writeValue(Parcel.java:2491) 
	at android.os.Parcel.writeValue(Parcel.java:2381) 
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1917) 
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1954) 
	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123) 
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139) 
	at android.os.Handler.handleCallback(Handler.java:958) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at android.os.Looper.loopOnce(Looper.java:230) 
	at android.os.Looper.loop(Looper.java:319) 
	at android.app.ActivityThread.main(ActivityThread.java:8919) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
```

I get same error when I make FadeTransition parcelable:
```
@Parcelize
final class FadeTransition: ScreenTransition, Parcelable {
    ...
}
```

project configurations:
```
[versions]
agp = "8.2.2"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
compose-plugin = "1.6.11"
kotlin = "2.0.21"
kotlinx-coroutines = "1.8.1"
voyager = "1.1.0-beta03"
parcelize = "0.9.0"
kotlin-parcelize = "2.1.0-RC"

[libraries]
parcelize = { module = "dev.icerock.moko:parcelize", version.ref = "parcelize" }

[plugins]
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-parcelize" }
```toml

**Comment by DevSrSouza** [comment]
Use Java Serializable instead at `FadeTransition`
