### ISSUE TITLE
Unable to parcelize parcelable objects

### ISSUE THREAD

**Issue by lcsphantom** [adrielcafe/voyager#78]
In the documentation [here](https://voyager.adriel.cafe/state-restoration) we are explained to use @Parcelize and Parcelable however when doing so, the app throws an exception when you tap home, leave the app or open another Intent:

`FATAL EXCEPTION: main
                                                                                                    Process: ca.redacted, PID: 10491
                                                                                                    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = ca....redacted)
                                                                                                    	at android.os.Parcel.writeSerializable(Parcel.java:2125)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:1895)
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1104)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:1844)
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1104)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:1844)
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1303)
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1056)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:1813)
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1303)
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1056)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:1813)
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987)
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1303)
                                                                                                    	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4969)
                                                                                                    	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8645)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
                                                                                                    Caused by: java.io.NotSerializableException: ca...redacted
                                                                                                    	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
                                                                                                    	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
                                                                                                    	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
                                                                                                    	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
                                                                                                    	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
                                                                                                    	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
                                                                                                    	at android.os.Parcel.writeSerializable(Parcel.java:2120)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:1895) 
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1104) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:1844) 
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1104) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:1844) 
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987) 
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620) 
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1303) 
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1056) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:1813) 
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987) 
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620) 
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1303) 
                                                                                                    	at android.os.Parcel.writeBundle(Parcel.java:1056) 
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:1813) 
                                                                                                    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:987) 
                                                                                                    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620) 
                                                                                                    	at android.os.Bundle.writeToParcel(Bundle.java:1303) 
                                                                                                    	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4969) 
                                                                                                    	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8645) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) `

In fact the example given in the documentation doesn't work.
Versions used:

`val voyager_version = 1.0.0-rc02`

```
    implementation "cafe.adriel.voyager:voyager-navigator:$voyager_version"
    implementation "cafe.adriel.voyager:voyager-androidx:$voyager_version"
    implementation "cafe.adriel.voyager:voyager-hilt:$voyager_version"
```

`   id org.jetbrains.kotlin.android version 1.7.0 apply false`
 
```
  ext {
        compose_ui_version = 1.2.0-rc01
        compose_compiler_version = 1.2.0
   }
```

I did see this thread: #https://github.com/adrielcafe/voyager/issues/59 but even when using something like:
```
@Parcelize
data class NavParam(
    var firstName: String = "",
): Parcelable

data class NewScreen(
    val navParam: NavParam
) : Screen {
}
```
The app still crashes.

**Comment by DjakaTechnology** [comment]
I also encountered this, for now I add Serializable into the mix to workaround this issue

@Parcelize
data class NavParam(
    var firstName: String = "",
): Parcelable, Serializable

**Comment by zakrodionov** [comment]
@adrielcafe @DevSrSouza @Syer10 
I tagged you guys, because you are the main maintainers of the code.
Please see this issue🙏🙏🙏

**Comment by Kashif-E** [comment]
Facing this on '1.0.0-rc02'

**Comment by Kashif-E** [comment]
if some one using it in a kmm app. you can do expect actual to get `java.io.Serilizable`
```
actual CommonSerializable = Serializable

expext CommonSerializable
```

and then 
```
data class SomeClass(val foo: String) : CommonSerializable
```

**Comment by ghostmane0404** [comment]
1.0.0-rc04 and it is still present. @adrielcafe is there any new on this theme?

**Comment by DevSrSouza** [comment]
The documentation was misleading, we have updated it with more samples and Multiplatform notice.
https://voyager.adriel.cafe/state-restoration

**Comment by KapilYadav-dev** [comment]
Any update on this guys ????

**Comment by Kashif-E** [comment]
@KapilYadav-dev  i have updated my comment that solves this issue

**Comment by KapilYadav-dev** [comment]
@Kashif-E  what about desktop and ios for their platform?

**Comment by DevSrSouza** [comment]
@KapilYadav-dev is just a plain interface in this case

`actual interface CommonSerializable`
