### ISSUE TITLE
[Hilt] [ViewModel] popUntil not working as expected?

### ISSUE THREAD

**Issue by michaldrabik** [adrielcafe/voyager#86]
Observed behavior:

- 3 destinations A, B, C - all AndroidScreen with Hilt ViewModels.
- Pushing A -> B -> C

When trying to use popUntil to A from C - the B screen and it's ViewModel are not being removed. If I try to push B again from A the ViewModel is the same instance holding latest state.

If I try to go A -> B -> pop -> A -> B everything is fine.

Is this expected? Propbably not - I'd expect behaviour described in docs:
![image](https://user-images.githubusercontent.com/11537045/195854936-6adfd272-18e4-4fc9-ad2e-70a5c6a7989e.png)
![image](https://user-images.githubusercontent.com/11537045/195854961-1c7ab15d-d6df-4fc1-9765-c0b94f3d97bc.png)

**Comment by Tolriq** [comment]
Reproduce and can confirm, this is caused by the internals and not that easy to fix.
The stack is OK this is the disposing that is wrong. Disposing is linked with the composable being removed and the action being a removal one.

So when you push C, B is removed from composition but since it's a push action it's not disposed. When you pop from C to A.
C is removed it's a removal action so it's disposed. But since B is not composed there's no trigger of the dispose and the viewmodel is kept.

This require some fundamental changes as current stack system does not carry the necessary info (single event for multiple pop / replace) @adrielcafe

**Comment by michaldrabik** [comment]
@Tolriq Thanks, makes sense. Unfortunately it seems like this project has been abandoned :/

**Comment by Tolriq** [comment]
@adrielcafe have no more time for personal project but I don't think it's officially abandoned. Maybe he can pop just to confirm that or not.

My main pain point currently is that it's multiplatform and IJ/AS does not properly handle composite builds for that case, making keep small changes until official fixes a real pain.

On the other hands there's not much other projects that works in the same way as this one. appyx still don't have hilt support.

**Comment by Syer10** [comment]
I've been working on a fork thats meant to be a bugfix fork(with iOS support). I'll can see if I can fix this

https://github.com/syer10/voyager

**Comment by michaldrabik** [comment]
@Syer10 Good to know. Let know if you need some assistance or something.

**Comment by Syer10** [comment]
Fixed in my fork for the next release 👍  https://github.com/Syer10/voyager/commit/81119e5c3036268835ad0769b35845c4991cebb4

**Comment by michaldrabik** [comment]
Sounds great. We will surely give it a go when released.

**Comment by michaldrabik** [comment]
@Syer10 Does you fork require extra setup? Getting `java.lang.IllegalArgumentException: CreationExtras must have a value by `SAVED_STATE_REGISTRY_OWNER_KEY` after migration.

**Comment by Syer10** [comment]
Can you post more of the exception? I'm not sure where that would be happening. Maybe make sure your Lifecycle library is updated

**Comment by michaldrabik** [comment]
Happens at `val viewModel = getViewModel<...>` seems like something to do with Transitions:


```
                                                         java.lang.IllegalArgumentException: CreationExtras must have a value by `SAVED_STATE_REGISTRY_OWNER_KEY`
                                                         	at androidx.lifecycle.SavedStateHandleSupport.createSavedStateHandle(SavedStateHandleSupport.kt:91)
                                                         	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:89)
                                                         	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:116)
                                                         	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                         	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                         	at ***.IntroductionScreen.Content(IntroductionScreen.kt:315)
                                                         	at cafe.adriel.voyager.transitions.ComposableSingletons$SlideTransitionKt$lambda-1$1.invoke(SlideTransition.kt:30)
```

```
Navigator(ScreenRegistry.get(initialScreen)) { navigator ->
            SlideTransition(navigator)
...
}
```

lifecycle version is latest `2.6.0-alpha03`

**Comment by michaldrabik** [comment]
Can do it tomorrow or you feel free to open by yourself now if you wish. Thanks
